version: '3.9'

services:

  catalog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-api
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__Default: Host=postgres;Port=5432;Database=catalogdb;Username=postgres;Password=postgres

      Jwt__Issuer: https://fiapgame-auth
      Jwt__Audience: fiapgame-clients
      Jwt__Key: super-secret-dev-key-min-32-chars

      RabbitMq__Host: rabbitmq
      RabbitMq__Username: guest
      RabbitMq__Password: guest
      RabbitMq__VirtualHost: /

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    restart: unless-stopped


  postgres:
    image: postgres:16
    container_name: catalog-postgres
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catalogdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped


  rabbitmq:
    image: rabbitmq:3-management
    container_name: catalog-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - catalog-api
    restart: unless-stopped


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped


volumes:
  pg_data:
  grafana_data: